- css/footerstyle.css
- css/menustyle.css
- css/nav_mob.css
- css/style.css
- index.html
> Десктоп і смартфон. Фон навигации (верхняе і ніжняе меню) #3e3e3e, должен быть везде #333333. #50
> fix: fix #50 `background into nav blocks` Фон верхнего и нижнего меню изменен на #333333

- css/footerstyle.css
В футере текст кнопки "ОК" изменен на #898989.
> fix: fix #56 change button text color

- css/footerstyle.css
Фон футера изменен на #333333.
> fix: fix #55 change footer background color

- css/footerstyle.css
- css/menustyle.css
- css/modal.css
Округление на всех кнопках на мобильных устройствах изменено на значение 3px.
> fix: fix #43 change button border radius on small screens

- css/menustyle.css
Десктоп. В навигации цвет при наведении заменен #d6ff32
> fix: fix #48 change navigation items color on hover

- css/footerstyle.css
- index.html
В футере инпут поиска изменен на инпут почты.
> fix: fix #39 change input type to 'email'

- css/menustyle.css
> Фон меню павінен мець празрыстасць як на макеце https://github.com/nastyafrosty/Falanster_new_website/blob/master/Main%20page/main%20desktop.psd
> fix: fix #72 `Дэсктоп. Фон меню павінен мець празрыстасць.`

- css/style.css
Fix, please check it
> @siarohin зробіце, каб такога не было?
як разумею тут таксама праблема ў тым, што малюнак як малюнак, а не бэкграўнд?
@amoebiusss
Collaborator
amoebiusss commented 42 minutes ago
Тут картинка как div с фоновой картинкой, но этот div спозиционирован с помощью margin, поэтому смещает соседний блок
> fix: fix #80 `Гарачыя праекты фоновая картинка слева смещает сам блок`

- css/style.css
> Калі ласка, зрабіце, каб назва "Гарачыя праекты" на мабілке і дэсктопе была #333333
Fixed.
> fix: fix #51 `Гарачыя праекты" на мабілке і дэсктопе была #333333`

- index.html
Добавлен вьюпорт-метатег с фиксированной шириной контента. Не уверена, что это исправляет проблему, т.к. нет реального девайса - только эмулятор. Нужно протестировать.
> fix: fix #57 отображение сайта в мобильном сафари

- css/blogstyle.css
- css/footerstyle.css
- index.html
@Omeljusik протестируйте, пожалуйста, и слейте, если все ок
> fix: fix #87 поправлена верстка блога

- css/footerstyle.css
> fix: поправлен отступ в футере на мобильных устройствах

- script.js
> так, але гэта пужае, ці можна перапрацаваць логіку, каб праверка была пасля націску на Ок
1. вводим емэйл - авточекер не работает (edited) 
2. нажимаем ОК (Enter) - начинает работать, подсвечивает емэйл
3. авточекер работает на каждое изменение символа (погаснет при вводе коррект емэйла) (edited)
> feat: check email field

- script.js
Reverts diglabby/Falanster-site#99
Адкачу змены, бо есць праблема. Калі аднойчы ўвела неверна, то пры выдаленні ўсяго тэкста, поле гасне, а калі зноў пачынаю проста набіраць адрас, то яно адразу загараецца чырвоным.
Трэба так:
1. Лепшы варыянт:
калі спачатку адрас уведзены неверна і націснулі ок, то поле падсвечваецца чырвоным да таго моманта, пакуль весь неверны адрас будзе выдалены з поля. Калі весь адрас выдалены - поле сіняе; Калі пачынае ўводзіцца зноў - поле застаецца сінім.  (зноў да націску на ок і калі есць памылка, то падсвечваецца, няма - пераход на саронку з завяршэннем падпіскі)
2. калі спачатку адрас уведзены неверна і націснулі ок, то поле падсвечваецца да таго моманта, пакуль не будзе ўведзена вернае значэнне і націснута ок. Потым гасне і зноў вяртаецца ў стан, калі пры …
> Revert "feat: check email field"

- css/menustyle.css
> Нет состояний hover/focus/active у кнопки "Уваход" в шапке #88 напрыклад павялічванне на 2 px пры навядзенне і загараніе аранжавым #ff6600 пры націску?
You can test it
> fix: fix #88 'Button Enter hover/active'

- css/menustyle.css
Гэта стварала багі ў Эксплорэре і Мазіле (кнопкі памяншаліся і здвігалі іншыя элементы)
> Update menustyle.css Прыбрала font-weight: normal пры націску на кнопку Уваход і Чытаць далей

- css/menustyle.css
Удалил состояние active у кнопки входа, т.к. состояние кнопки не меняется. Это рефакторинг последней правки, нет новых фич, работать будет также как сейчас.
> refactor: delete unnessasary Button style on active state

- css/menustyle.css
> fix: изменен цвет верхнего меню навигации — в соответствии с макетом

- css/menustyle.css
- css/style.css
Top light fix; bottom fix.
> При перешагивании по значкам в разделе меню внизу окна браузера появляется вспышка-полоса #117
> fix: fix #117

- index.html
> fix: fix #128 close unclosed form tag

- css/footerstyle.css
> Поле для ввода электронной почты имеет закругления 1рх #129
> fix: fix #129 'email input form border-radius 3px'

- css/footerstyle.css
Reverts diglabby/Falanster-site#121
> Revert "Issue/fix#111"

- css/footerstyle.css
- css/menustyle.css
- css/style.css
> fix: fix #113 удален глобальный стиль для body

- index.html
[Галоўная старонка] Адсутнічае полупразрыстасць пры навядзенні на Гарачы праект. #149
> fix: fix #149

- css/content.css
> Вялікая адлегласць паміж Назвай і аўтрам і датай публікацыі
> Але важна, каб цэнтраванне засталася паміж меню і шэрым прамавугольнікам.
> fix: fix #136

- css/footerstyle.css
> Футер. “Правілы сайта”, “FAQ”, “Зрабі ўнесак”, “Кантакты” отсутствует при наведении шрифт 20px, при нажатии цвет # ff6600 #181
> fix: fix #181

- css/blogstyle.css
> ## Гл.стр. Ссылка Усе падзеi не меняет цвет 
> Вложение: https://monosnap.com/file/cUcLOeda5WSX0a6RKtxzu8TWuKkjoA
Ожидаемый результат: все ссылки в тексте подчеркнуты, при наведении курсора на ссылку меняется цвет подчеркнутость остается, при нажатии на ссылку подчеркнутость убирается.
> fix: fix 180 `blog__more-link hover/active styles` (!! index tpl)

- css/content.css
> fix: fix #173 #179 добавлена тень блоку даты/статуса проекта

- organisation.html
- project-club.html
> 
* На старонке https://diglabby.github.io/Falanster-site/organisation.html трэба каб былі ўсе 9 картак, прэдпалагаецца, што больш ці меньш дакладна не будзе. Гэта стабільная лічба.
* У Праекты+Клубы https://diglabby.github.io/Falanster-site/project-club.html трэба дадаць яшчэ две карткі, бо праекты могуць папаўняцца і не заўседы іх будзе змяшчацца па тры як і ў блоге.
> fix: fix #190

- css/content.css
Fix: position
> [Унутраная. Смартфон] Не бачна статус праекта ці дату на першам экране. Дата падзеі ці статус праекта павінны заўседы адлюстроўвацца ў ніжнем правам вуглу першага экрана. #206
> fix: fix #206 `display events on mobile devices`

- css/content.css
Reverts diglabby/Falanster-site#207
> Revert "fix: fix #206 `display events on mobile devices`"

- css/content.css
> fix: fix #206

- css/style.css
> [Прамежкавая старонка. Смартфон] Зрабіць адлегласць паміж загалоўкам і першай карткай такога ж памера як ад меню да загалоўка.
> fix: fix #223

- css/pagination.css
> Вложение: https://monosnap.com/file/Zvu4BWltNj94K1Sqizu1kYewpIUN1k
Ожидаемый результат: Номер тек стр по центру
> fix: fix #229

- event.html
> Мобилка/Декстоп. Event. Не хватает запятой в прямоугольнике, где отображается дата и время события
> fix: fix #226

- css/style.css
> Десктоп. Фаланстер (промеж стр). Шрифт всех заголовков текста
> Ожидаемый результат: Ubuntu medium
> fix: fix #218

- css/content.css
> fix: fix #205 исправлены стили кнопки

- css/content.css
> fix: fix #202 remove focus style

- blog.html
- css/style.css
- organisation.html
- project-club.html
- Issue:  https://github.com/diglabby/Falanster-site/issues/233
> fix: fix #233 cover image

- css/content.css
Этот PR увеличит шрифт даты и автора для мобильной версии
Было:
Станет:
> fix: font size to banner__info position

- js/script.js
Подключение валидации емэйла на внутренние страницы. Сейчас только на главной.
Станет:
> fix: validate mail inside page
